### ISSUE TITLE
可以用作特征的是哪个字段里面的值

### ISSUE THREAD

**Issue by kejom-ou** [TencentGameMate/chinese_speech_pretrain#12]
你好，利用fairseq推理得到一个字典，该字典的那个字段是可以用作音频的特征？现在的字段有x，features等

**Comment by LiuShixing** [comment]
用x，x是最后一层的结果，feature是CNN层的结果

**Comment by kejom-ou** [comment]
好的，谢谢

**Comment by Hachiiiiii** [comment]
你好，请问fairseq怎么推理得到字典呀？最后一层的特征向量我提取出来是1024，看别的issue说应该是768，请问768应该怎么提取呢
