### ISSUE TITLE
vocab相关

### ISSUE THREAD

**Issue by wl1320310292** [TencentGameMate/chinese_speech_pretrain#3]
你好，下载的模型中没有提供vocab.json，而且我看config.json中的vocab_size是32，这个应该是英文的词汇表大小吧

**Comment by LiuShixing** [comment]
模型是无监督预训练的，没有经过asr微调，所以没有词表，huggingface模型的config.json里的词表相关参数是转换导出hf格式时默认参数，因为模型本身没这个参数，所以保留了默认值。不清楚的参数可以看fairseq版模型的cfg确认

**Comment by wl1320310292** [comment]
> 

没有

**Comment by wl1320310292** [comment]
> > 你好，下载的模型中没有提供vocab.json，而且我看config.json中的vocab_size是32，这个应该是英文的词汇表大小吧
> 
> 你好，请问有找到vocab.json词表吗，能分享下吗

没有，这版的模型并没有词表
