### ISSUE TITLE
可以同时提取中英文语音的特征吗

### ISSUE THREAD

**Issue by milely** [TencentGameMate/chinese_speech_pretrain#36]
感谢开源，请问这版预训练模型可以同时处理中英文吗，还是只支持中文呢

**Comment by LiuShixing** [comment]
只支持中文



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: milely ***@***.***&gt;
发送时间: 2023年5月6日 17:59
收件人: TencentGameMate/chinese_speech_pretrain ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [TencentGameMate/chinese_speech_pretrain] 可以同时提取中英文语音的特征吗 (Issue #36)





 
感谢开源，请问这版预训练模型可以同时处理中英文吗，还是只支持中文呢
