### ISSUE TITLE
Add WavLM

### ISSUE THREAD

**Issue by brian-gyh** [TencentGameMate/chinese_speech_pretrain#42]
您好，

这个工作非常的棒，但是我想知道你们是否有将 WavLM 模型添加到该库中的打算？

**Comment by LiuShixing** [comment]
没有计划



发自我的iPhone


------------------ Original ------------------
From: brian-gyh ***@***.***&gt;
Date: Mon,Aug 28,2023 6:10 PM
To: TencentGameMate/chinese_speech_pretrain ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [TencentGameMate/chinese_speech_pretrain] Add WavLM (Issue #42)





 
您好，
 
这个工作非常的棒，但是我想知道你们是否有将 WavLM 模型添加到该库中的打算？
