### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ChengsongLu** [TencentGameMate/chinese_speech_pretrain#48]
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte`

When call `feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained("hubert-large/chinese-hubert-large.pt")`

**Comment by ChengsongLu** [comment]
Why the hubert script use the Wav2Vec2FeatureExtractor as well

**Comment by ChengsongLu** [comment]
What is the different between 'chinese-hubert-large-fairseq-ckpt.pt' and 'pytorch_model.bin' in chinese-hubert-large? Which model should I use?

**Comment by LiuShixing** [comment]
带fairseq的是fairseq框架的模型，另一个是transformer框架，看你用的是哪个框架



发自我的iPhone


------------------ Original ------------------
From: ChengsongLu ***@***.***&gt;
Date: Thu,Feb 22,2024 6:49 PM
To: TencentGameMate/chinese_speech_pretrain ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [TencentGameMate/chinese_speech_pretrain] Error (Issue #48)
