### ISSUE TITLE
有没有更详细的教程

### ISSUE THREAD

**Issue by hello2013** [TencentGameMate/chinese_speech_pretrain#5]
比方说 按步骤执行某种任务样例等. 达到什么效果...这样才会有更多的粉丝.才会更快的发扬光大

**Comment by pengchengguo** [comment]
谢谢你的建议。我们会整理下下游 ESPnet 训练的配置文件和脚本，然后 push 上去，方便在 ESPnet 中结合预训练模型。

**Comment by pengchengguo** [comment]
你好，下游 ESPnet 训练配置文件已上传至 `espnet` 目录下。
