### ISSUE TITLE
About fairseq checkpoint link

### ISSUE THREAD

**Issue by godiclee** [TencentGameMate/chinese_speech_pretrain#6]
Hi, can you kindly provide links to fairseq model checkpoints outside pan.baidu.com? (restricted access) Thanks

**Comment by pengchengguo** [comment]
Hi @godiclee,

Which cloud disks are more available to you? We can upload the pre-trained models to other cloud disks (if we have accounts and the space limitation is enough :) )

**Comment by godiclee** [comment]
Thanks for your quick reply :)
google drive / onedrive / mega / dropbox seem to be fine

**Comment by LiuShixing** [comment]
We now provide fairseq checkpoint in huggingface model link, e.g chinese-wav2vec2-base-fairseq-ckpt.pt in https://huggingface.co/TencentGameMate/chinese-wav2vec2-base
