### ISSUE TITLE
HuBERT模型对应的kmeans模型

### ISSUE THREAD

**Issue by ziyichen-paii** [TencentGameMate/chinese_speech_pretrain#7]
你好，感谢你们提供的中文语音预训练模型。
请问能否提供训练HuBERT模型quantization用的kmeans模型，以及用作kmeans聚类的特征信息？谢谢。

**Comment by pengchengguo** [comment]
你好，HuBERT 不同阶段 kmeans 的 dict 和 model 已上传。用于 kmeans 的特征因为太大没法上传，可以自行提取（MFCC 或者 HuBERT 特定层输出）。

**Comment by ziyichen-paii** [comment]
> 你好，HuBERT 不同阶段 kmeans 的 dict 和 model 已上传。用于 kmeans 的特征因为太大没法上传，可以自行提取（MFCC 或者 HuBERT 特定层输出）。



> 你好，HuBERT 不同阶段 kmeans 的 dict 和 model 已上传。用于 kmeans 的特征因为太大没法上传，可以自行提取（MFCC 或者 HuBERT 特定层输出）。

非常感谢。

**Comment by Liujingxiu23** [comment]
小白不太明白 kmeans是如何使用的。是在提取hubert特征后，在使用hubert_kmeans下的模型提取一下吗？有例子不？
