### ISSUE TITLE
与原始版本预训练模型对比

### ISSUE THREAD

**Issue by zhangxueyangjuxie** [TencentGameMate/chinese_speech_pretrain#9]
你好，请问你们有在中文场景和原来的预训练模型做过详细对比吗？

**Comment by LiuShixing** [comment]
”原来的预训练模型“是指哪个模型呢？fairseq开放的XLSR吗，这个没有对比

**Comment by zhangxueyangjuxie** [comment]
对，就是开放的英文预训练模型， 感觉要证明下中文场景的asr或者sre等性能确实比他们的效果好，你们的模型才更好推广吧

**Comment by pengchengguo** [comment]
你好，关于 Meta AI 开源的 wav2vec 2.0 模型和 HuBERT 模型在 Aishell 中文 ASR 任务的效果，可以参考论文：“An Exploration of Self-Supervised Pretrained Representations for End-to-End Speech Recognition”，需要注意论文中预训练模型均为 large 模型，其中 wav2vec 2.0 是 960h librispeech 数据训练的，HuBERT 是 60kh librilight 数据训练的。

**Comment by zhangxueyangjuxie** [comment]
好的，感谢
